version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - "10000:10000"
      - "10001:10001"
    volumes:
      - ./backend:/app
    networks:
      - othello-net

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    networks:
      - othello-net

networks:
  othello-net:
